### ISSUE TITLE
OpenJdk not Supported under Windows (embedded-cassandra-junit5-test:3.0.3)

### ISSUE THREAD

**Issue by Toomy** [nosan/embedded-cassandra#100]
Hi
I have found out, that the usage of OpenJDK is not working for embedded-cassandra-junit5-test:3.0.3 under Windows 10. However it is working perfectly on Linux.
 
It is perfectly reproducible, as soon as one is selecting the Oracle JDK via the 
```
EmbeddedCassandraBuilder()
withArtifact(Artifact.ofVersion("4.0-alpha4"))
.withJavaHome(Paths.get("C:\\javasoft\\oracle\\Java\\jre1.8.0_251"))
```
the Junit 5 Test it running. If one select any OpenJDK ( no mather what Version between 8 and 13 ) it is not working. Instead it shows the following error when used 
* with OpenJDK 13:
-> Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer). Java 13 is not supported.
* with OpenJDK 11:
->Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer). Java 11.0.6 is not supported.

Thank you, Regards Markus

**Comment by nosan** [comment]
Hello @Toomy ,  

It seems like `Cassandra` scripts have a java version condition. I found several of them:
```
bin/cassandra.in.sh:        echo "Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer). Java $JVM_VERSION is not supported."
bin/cassandra.in.sh:        echo "Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer). Java 8 update $JVM_PATCH_VERSION is not supported."
bin/cassandra.in.sh:    echo "Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer)."
conf/cassandra-env.ps1:        echo "Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer). Java $env:JVM_VERSION is not supported."
tools/bin/cassandra.in.sh:        echo "Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer). Java $JVM_VERSION is not supported."
tools/bin/cassandra.in.sh:        echo "Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer). Java 8 update $JVM_PATCH_VERSION is not supported."
tools/bin/cassandra.in.sh:    echo "Cassandra 4.0 requires either Java 8 (update 151 or newer) or Java 11 (or newer)."

```
Unfortunately, I can't handle this on `Embedded Cassandra` side as this is a part of `Cassandra` source code.
