### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by dipeti** [nosan/embedded-cassandra#107]
Hi,

I have a scala project that I build under java 11 and my integration tests fail due to embedded-cassandra's lack of support. Do you have any plans for making it possible to run embedded-cassandra under java11?

**Comment by nosan** [comment]
Hello,
  have you tried 4.x.x-alpha versions?

**Comment by nosan** [comment]
Apache Cassandra 3.x.x does not support java 11, so you have to use  http://archive.apache.org/dist/cassandra/4.0-alpha4/
Version with java 11

**Comment by nosan** [comment]
See https://nosan.github.io/embedded-cassandra/#configure-version

**Comment by dipeti** [comment]
Hi, 
Apologies for my ignorance, was not aware that Cassandra 3.11 does not support java 11. Appreciate the prompt reply.

**Comment by hsn10** [comment]
Apache Cassandra 3.11 can be fixed to run on JDK 11

1. You need disk_access_mode: standard
2. remove sigar-bin
3. replace jamm with jamm-0.3.3.jar
