### ISSUE TITLE
Check that if Embedded Cassandra is already running that don't start a new instance

### ISSUE THREAD

**Issue by manuchadha1979** [nosan/embedded-cassandra#135]
Hi

Would it be possible to add a functionality which allows user to check that if Embedded Cassandra is already running then don't start a new version.

My test cases are organised into specs and the runner runs specs in parallel. Due to parallelism, each spec starts its version of Embedded Cassandra which overwhelms the machine. I can't order the execution of tests. So it will help me greatly if only one instance is stared and others just use it.

thanks

**Comment by nosan** [comment]
Hi @manuchadha1979

You can have a static instance of `Cassandra` and share it across all your tests. 

```java


public class CassandraInstance {

	private static volatile Cassandra cassandra;

	public Cassandra getOrCreate() {
		Cassandra cassandra = CassandraInstance.cassandra;
		if(cassandra==null){
			synchronized (this){
				cassandra = CassandraInstance.cassandra;
				if(cassandra==null){
					cassandra = new EmbeddedCassandraFactory().create();
					cassandra.start();
					CassandraInstance.cassandra = cassandra;
				}
			}
		}
		return cassandra;
	}

}
```
