### ISSUE TITLE
NoSuchMethodException in integration test

### ISSUE THREAD

**Issue by ThatGuy32** [nosan/embedded-cassandra#15]
Hi :)

first of all thanks for your work :)
I tried to integrate it in a spring project and in some tests it worked fine, but in some cases it throws a NoSuchMethodException.
im not sure how to reproduce it but it looks like spring is looking for a default constructor in EmbeddedCassandraConfiguration$EmbeddedClusterFactoryBean which is missing.
i am using Spring boot 2.1.0 M2/Spring 5.1.0.RC2 

any chances you know how to fix this? Maybe its really just a missing constructor?
thank you in advance :)

Here's the stacktrace:

Caused by: java.lang.NoSuchMethodException: com.github.nosan.embedded.cassandra.spring.EmbeddedCassandraConfiguration$EmbeddedClusterFactoryBean.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_181]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[na:1.8.0_181]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78) ~[spring-beans-5.1.0.RC2.jar:5.1.0.RC2]
	... 66 common frames omitted

**Comment by nosan** [comment]
Hi @ThatGuy32 , I've tried to reproduce this issue (see https://github.com/nosan/gh-15). 
Everything is ok. 
Could you please add the whole `stacktrace` or a sample.

Thanks in advance.

**Comment by ThatGuy32** [comment]
okay finally i could reproduce it
looks like it happens if spring-cloud dependencies are on classpath

sadly i am not allowed to add a bigger stacktrace, but there is nothing more anyway. 
i'll look if there's something wrong with our project or try to add a sample if i can reproduce it in a smaller project


thanks for the quick reply :)

**Comment by ThatGuy32** [comment]
i couldn't fix it

i added a sample (see ThatGuy32/embedded-cassandra@12fe4af321bf851d8d8973ee1504c86f0ae682de)
hope you can help me :)

**Comment by nosan** [comment]
Thanks for the sample @ThatGuy32 , seems like there is a bug with constructor injection in the `FactoryBean`.  
I'll fix it and let you know.

P.S. Sorry for inconvenience.

**Comment by nosan** [comment]
@ThatGuy32
`0.0.13` contains a fix.

**Comment by ThatGuy32** [comment]
it works now
Thanks!
