### ISSUE TITLE
fallback to cassandra.bat wont work

### ISSUE THREAD

**Issue by hsn10** [nosan/embedded-cassandra#183]
In https://github.com/nosan/embedded-cassandra/blob/df1e90f51f57b744ef5ec4968a3d9992bc7ce86c/src/main/java/com/github/nosan/embedded/cassandra/WindowsCassandraDatabase.java#L85
there is fallback to cassandra.bat but it does not work - cassandra.bat is not called. I copied my own cassandra.bat into bin/ directory and inspecting temporary copy shows it is there.
```
[info] ***** CASSANDRA STARTING *****
22:20:00.244 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra - C:\Users\hsn\AppData\Local\Temp\apache-cassandra-4.0-rc1-5664624711481308455\bin\cassandra.ps1 : The term 'C:\Users\hsn
22:20:00.253 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra - \AppData\Local\Temp\apache-cassandra-4.0-rc1-5664624711481308455\bin\cassandra.ps1' is not recognized as the name of a
22:20:00.255 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra - cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify t
22:20:00.256 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra - hat the path is correct and try again.
22:20:00.258 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra - At line:1 char:1
22:20:00.258 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra - + C:\Users\hsn\AppData\Local\Temp\apache-cassandra-4.0-rc1-566462471148 ...
22:20:00.260 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra - + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
22:20:00.261 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra -     + CategoryInfo          : ObjectNotFound: (C:\Users\hsn\Ap...n\cassandra.ps1:String) [], CommandNotFoundException
22:20:00.262 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra -     + FullyQualifiedErrorId : CommandNotFoundException
22:20:00.263 [cassandra-0:bin/cassandra.ps1:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra -
```

**Comment by nosan** [comment]
Hi @hsn10 
Could you please share your `cassandra.bat`?

**Comment by hsn10** [comment]
[cassandra.txt](https://github.com/nosan/embedded-cassandra/files/6410345/cassandra.txt)

**Comment by hsn10** [comment]
Just make name of file we are going to execute configurable and make configurable its arguments as well

**Comment by nosan** [comment]
@hsn10 Your issue has been fixed, you can try to use `4.0.3-SNAPSHOT`

**Comment by hsn10** [comment]
This error input line too long is from your library?
```
[info] ***** CASSANDRA STARTING *****
14:01:28.188 [cassandra-0:bin/cassandra.bat:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra - The input line is too long.
14:01:28.196 [cassandra-0:bin/cassandra.bat:ERR] ERROR com.github.nosan.embedded.cassandra.Cassandra - The syntax of the command is incorrect.
[info] ***** !!! cassandra start failed *****     
```

**Comment by nosan** [comment]
No, it is from script.

**Comment by hsn10** [comment]
You creating too long directory names. It works when renamed to something shorter like C:\users\hsn\local settings\temp\123

**Comment by nosan** [comment]
Temporary directory is being used by default,  you can specify your own working directory to be used.

**Comment by nosan** [comment]
https://nosan.github.io/embedded-cassandra/4.0.2/#working-directory

**Comment by hsn10** [comment]
Temporary directory is fine, other software is using that too but you are creating too long last component of directory name and it will fail to fit windows path limit.

**Comment by nosan** [comment]
```\AppData\Local\Temp\apache-cassandra-4.0-rc1-5664624711481308455\bin\cassandra.ps1```  is 82 characters long.

Windows path limit is 260. I don't see any issue with the last component, if it does not fit you, there is a way to override it.

**Comment by hsn10** [comment]
There is 8191 characters command line limit
https://docs.microsoft.com/cs-CZ/troubleshoot/windows-client/shell-experience/command-line-string-limitation

Cassandra.bat adds all JAR files to classpath making it too long and hitting that limit. That (82 characters + user home directory size) will be repeated many times.
