### ISSUE TITLE
Configuration file is not generated properly on windows

### ISSUE THREAD

**Issue by hsn10** [nosan/embedded-cassandra#185]
On windows original config file _cassandra.yaml_ is not overwritten by generated config. Inspection of .\conf directory shows (likely) temporary files _20digits-cassandra.yaml_.

I guess on windows you cant rename file if target  _cassandra.yaml_ exists. Tjere is also possible timing issue caused by antivirus scan. 

I propose fix

1. Write and close that temporary file
2. Wait 1 sec to give time antivirus to scan
3. delete original config
4. rename temporary file to final name

**Comment by nosan** [comment]
It was done intentionally and will not be changed.

**Comment by hsn10** [comment]
How do you signal to cassandra to use alternative configuration file, then?

You don't pass it on command line
https://github.com/nosan/embedded-cassandra/blob/963e50f17216923dba5c3f81725a0a91a38c9f97/src/main/java/com/github/nosan/embedded/cassandra/WindowsCassandraDatabase.java#L119

**Comment by nosan** [comment]
https://github.com/nosan/embedded-cassandra/blob/82f14640ae78df7c3728ae4c1dfb546abb002979/src/main/java/com/github/nosan/embedded/cassandra/DefaultCassandraDatabaseFactory.java#L98

https://github.com/nosan/embedded-cassandra/blob/82f14640ae78df7c3728ae4c1dfb546abb002979/src/main/java/com/github/nosan/embedded/cassandra/DefaultCassandraDatabaseFactory.java#L114


`JVM_EXTRA_OPTS` allows to pass extra `JVM/System` properties, and `-Dcassandra.config` one of them.
