### ISSUE TITLE
Running integration test on Bamboo, complains about running as root

### ISSUE THREAD

**Issue by bjorntorewiken** [nosan/embedded-cassandra#19]
Hi, thanks for the great work. I'm using the @EmbeddedCassandra (v 1.1.1 of the lib) annotation in my integration test, and it is working perfectly when running locally at my Mac. However, when trying to run the test as part of the build process on Bamboo it complains about being run as root, and Cassandra won't start.

```
Running Cassandra as root user or group is not recommended - please start Cassandra using a different system user.
If you really want to force running Cassandra as root, use -R command line option.
```

Is there any common solution to get past this? By configuration, or even being able to supply the -R option in some way.

**Comment by nosan** [comment]
Hey @bjorntorewiken,
I'm trying to add this functionality today. 
I let you know

**Comment by nosan** [comment]
https://github.com/nosan/embedded-cassandra/commit/7d2585ccb8cd380a6e2ae39cc93cf5c2b300fada

**Comment by bjorntorewiken** [comment]
Thanks for the quick response! I will give it a try tomorrow and get back to you.
