### ISSUE TITLE
Random ports

### ISSUE THREAD

**Issue by ThatGuy32** [nosan/embedded-cassandra#28]
Hi,

is it possible to run EmbeddedCassandra with random ports?
We use different test tags and it looks like gradle runs each tag in parallel, even though parallel build is disabled, so we get the following error:
java.net.BindException: Address already in use: JVM_Bind
because the port is already used

I saw i can set the ports in v2 and tried to set it to 0, but then spring doesn't know the (random) ports.

Is it possible to randomize the ports somehow? And if not, do you plan to support this in future versions?

Thanks in advance

**Comment by nosan** [comment]
Hello, 
Yes, it is possible to randomize ports, using `0` for port values. 
If you use `Spring` you can do this via:
```java
@ContextConfiguration
@ExtendWith(SpringExtension.class)
@EmbeddedCassandra(scripts = "/schema.cql", jmxLocalPort = "0", port = "0", storagePort = "0", rpcPort = "0")
class EmbeddedCassandraTests {

	@Test
	void testYourCode() {
	}

	@Configuration
	static class ClusterConfiguration {

		@Bean
		public Cluster cassandraCluster(TestCassandra cassandra) {
			return new ClusterFactory().create(cassandra.getSettings());
		}

	}

}

```

If you use `Spring Boot` you can do something like this:


```java

@SpringBootTest
@EmbeddedCassandra(scripts = "/schema.cql", jmxLocalPort = "0", port = "0", storagePort = "0", rpcPort = "0")
class EmbeddedCassandraTests {

	@Test
	void testYourCode() {
	}

	@Configuration
	static class ClusterBuilderCustomizerConfiguration {

		@Bean
		ClusterBuilderCustomizer embeddedClusterCustomizer(TestCassandra cassandra) {
			return builder -> {
				Settings settings = cassandra.getSettings();
				Integer port = settings.portOrSslPort().orElse(null);
				InetAddress address = settings.address().orElse(null);
				if (port != null && address != null) {
					builder.withPort(port).addContactPoints(address);
				}
			};
		}

	}

}
```

Or you can use this project:  https://github.com/nosan/cassandra-test-spring-boot
This project contains a slice `@DataCassandraTest` annotation that can be helpful to test `Cassandra Components`

**Comment by ThatGuy32** [comment]
The static Configuration class fixed it, couldn't find it in the wiki

Thanks a lot, i will close the issue then
