### ISSUE TITLE
Provide a way to register TypeCodecs

### ISSUE THREAD

**Issue by ratcashdev** [nosan/embedded-cassandra#32]
Using the `TestCassandra` there's no way to register a type-codec before the session is built and returned.

Currently the only way is a workaround:
```
        CqlSession session = (CqlSession) cassandra.getConnection().get();
        CqlSession customizedSession = CqlSession.builder()
                .withConfigLoader(session.getContext().getConfigLoader())
                .addTypeCodecs(new MyTypeCodec())
                .build();
        session.close();
```

**Comment by nosan** [comment]
Hello,
You are able to override an embedded connection.
```java
import com.datastax.oss.driver.api.core.CqlSession;
import com.datastax.oss.driver.api.core.CqlSessionBuilder;

import com.github.nosan.embedded.cassandra.Settings;

class Scratch {

	public static void main(String[] args) {
		TestCassandra testCassandra = new TestCassandra() {

			@Override
			protected Connection createConnection() {
				Settings settings = getSettings();
				TypeCodecCqlSessionFactory sessionFactory = new TypeCodecCqlSessionFactory();
				return new CqlSessionConnection(sessionFactory.create(settings));
			}
		};
	}

	static class TypeCodecCqlSessionFactory extends CqlSessionFactory {

		@Override
		protected CqlSession buildCqlSession(CqlSessionBuilder sessionBuilder) {
			sessionBuilder.addTypeCodecs(new MyTypeCodec());
			return super.buildCqlSession(sessionBuilder);
		}

	}

}
```

**Comment by nosan** [comment]
Does it work for you?

**Comment by nosan** [comment]
@ratcashdev 
Currently, `CqlSessionFactory` does not provide a way to add type codec directly. 
I think the following method could be useful for you.
 ```java
	/**
	 * Registers additional codecs for custom type mappings.
	 *
	 * @param typeCodecs type codes
	 * @since 2.0.4
	 */
	public void addTypeCodecs(TypeCodec<?>... typeCodecs) {
		this.typeCodecs.addAll(Arrays.asList(typeCodecs));
	}
```

Please let me know what you think.
Thanks

**Comment by ratcashdev** [comment]
@nosan Hi, thanks for the quick feedback.
The example with the `TypeCodecCqlSessionFactory` worked, but it seems quite verbose to do such a simple things.
As for the `addTypeCodecs` method, that sounds better, but still way to deep, honestly (subclassing `TestCassandra` and afterwards using the method exsposed by the `CqlSessionFactory`). My work-around seems to be least amount of lines (only 5). How about adding a list of Codecs to the `TestCassandra` constructor directly?

**Comment by nosan** [comment]
Thank you for your feedback @ratcashdev.

I had not been planning to have a way to get a connection to the `Cassandra` until version `2.0.2`, but then I realized that it should be a way to configure connection before running CQL scripts, thus I added `createConnection` and `getConnection` methods. I did not have a better choice to do this except subclassing `TestCassandra` otherwise I would break the code. 

I know it looks verbose and ugly, but I can not offer you more at the moment except what I mentioned before (`CqlSessionFactory.addTypeCodecs(...)`)


> Update: realized doing it directly inside TestCassandra is a bit complicated.
Wouldn't it be easier to have 2 entry points? TestCassandra3 and TestCassandra4?

Thank you for the suggestion, but unfortunately,  
`TestCassandra` is used by `@EmbeddedCassandra`, `CassandraRule`, `CassandraExtension` and `CassandraTestNG` classes and adding a new class would not fix an issue. 

As a workaround,  you can implement your own `TestCassandra`:

```java




public class TestCassandra0 extends TestCassandra {

	public TestCassandra0() {
		super();
	}

	public TestCassandra0(CqlScript... scripts) {
		super(scripts);
	}

	public TestCassandra0(CassandraFactory cassandraFactory, CqlScript... scripts) {
		super(cassandraFactory, scripts);
	}

	@Override
	public CqlSessionConnection getConnection() {
		return (CqlSessionConnection) super.getConnection();
	}

	@Override
	protected CqlSessionConnection createConnection() {
		CqlSession session = new CqlSessionFactory0().create(getSettings());
		return new CqlSessionConnection(session);
	}

	private static final class CqlSessionFactory0 extends CqlSessionFactory {

		@Override
		protected CqlSession buildCqlSession(CqlSessionBuilder sessionBuilder) {
			//configure type codec
			return super.buildCqlSession(sessionBuilder);
		}

	}

}


class Scratch {

	public static void main(String[] args) {
		TestCassandra0 testCassandra = new TestCassandra0(classpath("schema.cql"));
		//
		CqlSession session = testCassandra.getConnection().get();
	}

}


```

If you have any ideas about how it could be done, please share with me.

**Comment by ratcashdev** [comment]
@nosan thanks, I think I will go with this latest suggestion.

**Comment by nosan** [comment]
@ratcashdev,
 Since **2.0.4**:
```java
import com.github.nosan.embedded.cassandra.cql.CqlScript;
import com.github.nosan.embedded.cassandra.test.CqlSessionConnectionFactory;
import com.github.nosan.embedded.cassandra.test.CqlSessionFactory;
import com.github.nosan.embedded.cassandra.test.TestCassandra;

class Scratch {

	public static void main(String[] args) {
		CqlSessionFactory sessionFactory = new CqlSessionFactory();
		sessionFactory.addTypeCodecs(/*type code*/);
		TestCassandra testCassandra = new TestCassandra(new CqlSessionConnectionFactory(sessionFactory),
				CqlScript.classpath("schema.cql"));
		testCassandra.start();

		try {
			CqlSession session = testCassandra.getNativeConnection(CqlSession.class);
			//...
		}
		finally {
			testCassandra.stop();
		}
	}

}

```

Hope, it would be useful for you.

**Comment by nosan** [comment]
Btw, you can use `2.0.4-SNAPSHOT` version if you want to have this feature now.

**Comment by ratcashdev** [comment]
perfect, thank you!
