### ISSUE TITLE
cassandra 5.0

### ISSUE THREAD

**Issue by JusticeN** [nosan/embedded-cassandra#375]
Hi,

is there any plan to build a compatible Cassandra 5.0 version?

thank you in advance
Justice

**Comment by nosan** [comment]
Hello, 
I checked today in the morning 5.0-beta1 and it worked fine.

**Comment by JusticeN** [comment]
how can i test it too please ? 
there is actually no 5 versions in maven repo

i am excited to test vector search

**Comment by nosan** [comment]
```java

	Cassandra cassandra = new CassandraBuilder()
				.version("5.0-beta1")
				.build();

		cassandra.start();

		try {
                   //your tests :) 
		}
		finally {
			cassandra.stop();
		}
		
```

**Comment by JusticeN** [comment]
thank you
