### ISSUE TITLE
Unable to set Cassandra's environment variables

### ISSUE THREAD

**Issue by pauloborges** [nosan/embedded-cassandra#44]
Hi! First of all, thanks for such a valuable project!

I need to set some environment variables to specify how much memory Cassandra should use (`MAX_HEAP_SIZE` and `HEAP_NEWSIZE`), but it seems that is no API for specifying them.

Would you consider this feature?

**Comment by nosan** [comment]
Hi, have you tried to use `jvmOptions` ? I believe that you are able to pass `-Xmx, -Xms, -Xss` options via this property. 
Please let me know whether it works for you or not. 
Thanks

P.S.

```java
LocalCassandraFactory factory = new LocalCassandraFactory();
factory.getJvmOptions().add(...);

```

**Comment by pauloborges** [comment]
Unfortunately, this wouldn't work for me as I need the variables to be set to avoid [this particular branch on `cassandra-env.sh`](https://github.com/apache/cassandra/blob/cassandra-3.0/conf/cassandra-env.sh#L171-L172) due to limitations on the test environment I'm using ([it doesn't have `free`](https://github.com/apache/cassandra/blob/cassandra-3.0/conf/cassandra-env.sh#L21) and I don't have the capacity to change this).

**Comment by nosan** [comment]
Thanks for feedback, @pauloborges 
I am going to add this feature in `2.0.4` milestone.

**Comment by nosan** [comment]
Hi, @pauloborges 
Environment variables feature has been added. (you can try it with `2.0.4-SNAPSHOT` version)
```java
LocalCassandraFactory cassandraFactory = new LocalCassandraFactory();
cassandraFactory.getEnvironmentVariables().put("NAME", "VALUE");
```
Thanks
