### ISSUE TITLE
Bump 4.1 branch dep >= cassandra-4.1.6 because of incompatible changes in CASSANDRA-19534

### ISSUE THREAD

**Issue by 0x62ash** [nosan/embedded-cassandra#444]

**Comment by nosan** [comment]
Could you please describe what the issue is about?

**Comment by 0x62ash** [comment]
[I](https://github.com/instaclustr/cassandra-ldap/pull/51)
cassandra-ldap can't be tested on current embedded-cassandra version

**Comment by nosan** [comment]
@0x62ash 
https://github.com/nosan/embedded-cassandra/releases/tag/4.1.1

```xml
  <dependency>
        <groupId>com.github.nosan</groupId>
        <artifactId>embedded-cassandra</artifactId>
        <version>4.1.1</version>
    </dependency>
```

Bump to Apache Cassandra **4.1.7**

**Comment by 0x62ash** [comment]
Thank you

**Comment by nosan** [comment]
`embedded-cassandra:4.1.1` has the following compile dependencies:

```xml

<dependecies>
    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-compress</artifactId>
        <version>1.27.0</version>
    </dependency>
    <dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>2.2</version>
    </dependency>
</dependecies>

```
Looks like you have library conflicts.

**Comment by nosan** [comment]
And also, How `testcontainers` related to this project? 
Embedded Cassandra project does not use `testcontainers`.

**Comment by 0x62ash** [comment]
You are right.
I dug deeper and I see now that even with the old version of embedded-cassandra it was possible to test.
Thank you for support any way.

**Comment by nosan** [comment]
No problem :)
