### ISSUE TITLE
This is not an embedded Cassandra

### ISSUE THREAD

**Issue by sbespalov** [nosan/embedded-cassandra#49]
Correct me if I wrong but this project seems not allows to start Cassandra instance as embedded service. By "embedded" I assume that it should be started within same JVM from which it was started. In fact it use external `java.lang.Process` which is more like Java wrapper for Cassandra process.
If it so then probably better to mention this in project readme for not to confuse people.

**Comment by nosan** [comment]
Hi @sbespalov,
I think it is a good idea to update documentation and mention that the project does not start `Cassandra` within the same JVM.

Regarding naming, it is quite a controversial question, what I mean, there are a lot of projects that have the same `embedded` prefix and they use the same approach (`java.lang.Process`).

**Comment by nosan** [comment]
> Also renaming the project can make it more clear and popular for people which want exactly the java process wrapper for Cassandra.

I'm not sure that is possible. 
In any case, thank you very much for your feedback!
