### ISSUE TITLE
Question: Reusing cassandra instances through @ContextHierarchy

### ISSUE THREAD

**Issue by jonenst** [nosan/embedded-cassandra#80]
Hi,
I'm using @EmbeddedCassandra and I want to start only one cassandra for a bunch of classes. If the context is cached between two classes (when they have the exact same context configuration), then I get what I want.

However, it's hard to make sure that all classes have the same context (for example, using @MockBean forces a new context creation for each test class). I think that using @ContextHierarchy is the proper solution here, with a parent context holding the @EmbeddedCassandra beans and child context holding the @MockBeans getting recreated. Do you have a working example of using @ContextHierarchy to use a single cassandra instance accross multiple classes ? You could also add it to the docs.

Thanks,
Jon

**Comment by nosan** [comment]
Hi @jonenst,
Unfortunately, it is not possible to use `@ContextHierarchy` with `@EmbeddedCassandra`.

`@EmbeddedCassandra` uses the `EmbeddedCassandraContextCustomizer` under the hood.
This `ContextCustomizer` registers `Cassandra`, `CassandraConnection` beans for the provided context.
 If you want to have `ApplicationContext` hierarchy, then you will probably have several `ApplicationContext`:

```
--- ParentApplicationContext 
       --- ChildApplicationContext1
       ---  ...
       --- ChildApplicationContext M
```

In that case, `EmbeddedCassandraContextCustomizer` will be invoked (ParentContext + N * ChildContext) and it seems that is not exactly what you want.

In other words, you cannot use `@EmbeddedCassandra`  for that purpose, hence you should provide your own `CassandraConfiguration`

```java

@ContextHierarchy(@ContextConfiguration(classes = {EmbeddedCassandraConfiguration.class}))
@ExtendWith(SpringExtension.class)
public abstract class AbstractCassandraTests {

}

@Configuration(proxyBeanMethods = false)
class EmbeddedCassandraConfiguration {

	@Bean(initMethod = "start", destroyMethod = "stop")
	Cassandra cassandra(CassandraFactory cassandraFactory) {
		return cassandraFactory.create();
	}

	@Bean
	CassandraFactory cassandraFactory() {
		return new EmbeddedCassandraFactory();
	}

}


```

See this example:
https://github.com/nosan/embedded-cassandra-spring-context-hierarchy-example

**Comment by jonenst** [comment]
Hi @nosan , thanks for the quick reply, it's awesome. I needed to add the surefire version to your example repo to get maven to run the junit5 tests, otherwise it works great.
```diff
diff --git a/pom.xml b/pom.xml
index 8b19a47..1f59471 100644
--- a/pom.xml
+++ b/pom.xml
@@ -67,4 +67,9 @@
                 </configuration>
             </plugin>
+            <plugin>
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-surefire-plugin</artifactId>
+                <version>2.22.2</version>
+            </plugin>
         </plugins>
     </build>
```

 Thanks a lot for the help!
In my case, I already had mandatory base classes so I couldn't use your setup exactly like that, but using the following works just as well (it works with classes using your base class too):
```java
@ContextHierarchy({
    @ContextConfiguration(classes = {EmbeddedCassandraConfiguration.class, CassandraConfiguration.class}),
    @ContextConfiguration(...)
})
```

**Comment by nosan** [comment]
Thanks a lot for your feedback @jonenst  👍 
Yeah, it seems I've forgotten to add the surefire-plugin version. My bad.

I've added the correct version and pushed!
Now, it should work out-of-the-box. 

If you have any questions, feel free to ask! I will be glad to help.
