### ISSUE TITLE
Why force the proxy to NO_PROXY by default ?

### ISSUE THREAD

**Issue by jonenst** [nosan/embedded-cassandra#85]
Hi,
in https://github.com/nosan/embedded-cassandra/blob/0d67aa26605d0231cb98829fbe906d8df3c887f9/embedded-cassandra/src/main/java/com/github/nosan/embedded/cassandra/artifact/RemoteArtifact.java#L99

the default Proxy is NO_PROXY, for example when using the simple
```Artifact.ofVersion("XXX")```.

Sometimes, the same code must be run with or without a proxy. In such cases, It's nice that HttpURLConnection automatically picks up the -DproxyHost and -DproxyPort.

Maybe you could leave the proxy to null and in the connect method do
if (proxy != null) {
  url.openConnection(proxy);
} else {
  url.openConnection(); 
}
?

Cheers,
Jon

**Comment by nosan** [comment]
Hi @jonenst,
Good catch, I will follow your suggest! :)
