### ISSUE TITLE
Autodetecting cassandra version

### ISSUE THREAD

**Issue by jonenst** [nosan/embedded-cassandra#86]
Hi,
In the docs, it says
> 4.4. Run with Java 13
There are several ways to use Java 13:
    Use Apache-Cassandra 4.0-alpha3 version

But a few days ago (2020-04-24) 4.0-alpha4 was published and 4.0-alpha3 removed.
Maybe adding version discovery functionality would be good ? What do you think ? The simplest idea would be a "LATEST", but more complex versions are also possible. This would prevent things from breaking when new versions are released (at the cost of making the tests not very reproducible)

Cheers,
Jon

**Comment by triplem** [comment]
documentation is always static, but the world around it is usually not. an easier solution then the one described above would be to mention, to use at least a cassandra 4.x version. I guess, if somebody is using JDK13 and cassandra she should be able to determine the latest available version.

**Comment by jonenst** [comment]
But hardcoding a version means the code breaks whenever cassandra releases a new alpha. If you want the test to work without changes, you need code to lookup the latest version. Since it's the official workaround today to use with java11+, maybe embedded-cassandra can host this code. Otherwise everyone has to write it.

**Comment by triplem** [comment]
Well, it is an alpha and you should know, what this means ;-)

**Comment by nosan** [comment]
Hi @jonenst,

Thanks for this issue, but for this major version, I am not planning to add such a feature.

Regarding documentation as @triplem  said, is a static text and unfortunately, it should be fixed manually :(
