### ISSUE TITLE
Keyspace problem

### ISSUE THREAD

**Issue by triplem** [nosan/embedded-cassandra#87]
could be, that i have misunderstood something, but I am getting an error, if I use embedded-cassandra  together with datastax-driver 4.5.1 and cassandra 4.0-alpha4.
as soon as I do start the test, I do get an error, that the keyspace configured in my application.conf (outside of the test-directory) is not existing. this is true, because on starting the embedded-cassandra, no keyspace is available. Now I have removed this setting (session-keyspace) from my application.conf and create the keyspace via a CqlDataset. This seems to work fine, but I would like to use the keyspace in the application.conf to be able to make the keyspace configurable. 
There any way, to start the driver for the initial CQL-Loading without those settings, and only later use this config in a second phase, when I do insert and select data?
my test setup (using kotlin) and junit5 is looking something like:

---
    companion object {
        @JvmField
        var cqlSessionCassandraConnectionFactory = CqlSessionCassandraConnectionFactory()

        val logger = LoggerFactory.getLogger(RepositoryTest::class.java)

        @JvmField
        @RegisterExtension
        val cassandraExtension = CassandraExtension()
            .withCassandraFactory(EmbeddedCassandraFactory().apply {
                setArtifact(Artifact.ofVersion("4.0-alpha4"))
            })
            .withCqlDataSet(CqlDataSet.ofClasspaths("test.cql"))

        @BeforeAll
        @JvmStatic
        internal fun beforeAll() {
            // add keyspace to cqlSession to avoid using keyspace in queries
            cqlSessionCassandraConnectionFactory.sessionBuilderCustomizers +=
                Consumer { it.withKeyspace("kcd") }
        }
    }
---

great project by the way. i do like it.

**Comment by nosan** [comment]
Hi @triplem,
When you are using `withKeyspace` it means that you want to connect to an existing keyspace, so
this keyspace must be created before.

You can use 2 different connections. First for schema migration and the second one for regular usage (here you can use `withKeyspace`).
Note, that the second connection should be created when Cassandra already has this keyspace.

**Comment by triplem** [comment]
Yeah, I understand your statement. Just one more question. How to avoid reading the application.conf and the datastax properties in there or to overwrite the keyspace entry in there?

**Comment by nosan** [comment]
Actually, I don't know :) Did you try to use `DefaultProgrammaticDriverConfigLoaderBuilder`? 
Or maybe it is possible to use a different profile? As far as I know, it is possible to have different profiles.
