### ISSUE TITLE
Allow to configure if working directory should be deleted on exit

### ISSUE THREAD

**Issue by Traderjoe95** [nosan/embedded-cassandra#94]
At the moment, it is not possible to choose to not delete the working directory when stopping the embedded Cassandra. In my use case (drop in replacement for a real Cassandra), I still need persistence of the stored data, even when using the embedded Cassandra.

As far as I have seen, there has been an option to configure that behavior in the past. Would it be possible to reimplement that?

**Comment by nosan** [comment]
Hi @Traderjoe95,

it is not a big deal to add this property, but I think you can achieve this with the following configuration properties:

**cdc_raw_directory** 
The directory where the CDC log is stored. 

**commitlog_directory** 
The directory where the commit log is stored. 


**data_file_directories** 
The directory location where table data is stored (in SSTables). Cassandra distributes data evenly across the location, subject to the granularity of the configured compaction strategy. 

**saved_caches_directory** 
The directory location where table key and row caches are stored. 

For instance:

```java

EmbeddedCassandraFactory cassandraFactory = new EmbeddedCassandraFactory();
cassandraFactory.getConfigProperties().put("data_file_directories", Paths.get("..."));

```
